# Site settings
title: Sy Blog
SEOTitle: 索源的博客 | Sy Blog
header-img: img/home-bg.jpg
email: 949809811@qq.com
description: "关于程序与设计、黑客与画家 | 索源，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @Sy索源 的个人博客，与你一起发现更大的世界。"
keyword: "索源, Sy索源, Sy, Sy, @Sy, 黄玄的博客, Hux Blog, 博客, 个人网站, 互联网, Web, C#, Unity, 设计"
url: "https://glassgame.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     Sy
zhihu_username:     Sy
github_username:    Sy
twitter_username:   Sy
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Infinite Shield  Inifinite Posibility<br>仍然相信"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "冯乐乐",
        href: "https://candycat1992.github.io/"
    },{
        title: "Unity Blog",
        href: "https://blogs.unity3d.com/?_ga=2.188769128.292273437.1571133820-1076233474.1568628049"
    },{
        title: "雨松MOMO",
        href: "https://www.xuanyusong.com"
    },{
        title: "U3d百度贴吧",
        href: "http://tieba.baidu.com/f?kw=unity3d"
    },{
        title: "郑洪智",
        href: "https://www.jianshu.com/u/df7bee87ffe2"
    }
]
